module.exports =
  [ { lane: 'standard',
    delay: 120,
    type: 'vehicular',
    port: 'san_ysidro' },
  { lane: 'sentri',
    delay: 15,
    type: 'vehicular',
    port: 'san_ysidro' },
  { lane: 'readylane',
    delay: 70,
    type: 'vehicular',
    port: 'san_ysidro' },
  { lane: 'standard',
    delay: 70,
    type: 'pedestrian',
    port: 'san_ysidro' },
  { lane: 'readylane',
    delay: 40,
    type: 'pedestrian',
    port: 'san_ysidro' } ]